language: php
dist: trusty

php:
- 5.6
- hhvm
- 7

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist

script:
- vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
